#Home

loc_new_request = "css:.mat-mdc-tooltip-trigger"
loc_status_new_request = "css:.mat-mdc-tooltip-trigger.retangulo.statusColor4"
loc_title_internship = "css:.tituloEstagio"
loc_cont_internship = "css:.cardConteudo"
loc_edit_doc_button = "xpath://span[contains(text(),'Editar documentos')]"
loc_details_request = "xpath://span[contains(text(),'Detalhes')]"
loc_status_approved_request = "css:.mat-mdc-tooltip-trigger.retangulo.statusColor1"
loc_send_report_button = "xpath://span[contains(text(),'Enviar relatório final')]"
loc_download_docs_button = "xpath://span[contains(text(),'Baixar documentos')]"
loc_approved_details_request = "css:.retanguloStatus.statusColor1"
loc_step1_details_request = "xpath://div[@class='step']/span[contains(text(),'Envio de documentos')]"
loc_step2_details_request = "xpath://div[@class='step']/span[contains(text(),'Análise setor de estágio')]"
loc_step3_details_request = "xpath://div[@class='step']/span[contains(text(),'Assinatura Coordenador de curso')]"
loc_step4_details_request = "xpath://div[@class='step']/span[contains(text(),'Assinatura Diretor')]"
loc_step5_details_request = "xpath://div[@class='step']/span[contains(text(),'Processo de assinatura Finalizado')]"
loc_completed_details_request = "xpath://div[@class='etapa']/span[contains(text(),'Concluído')]"
loc_status_processing_request = "xpath://span[text()='Processando']"
loc_logout = "css:.logout"
loc_status_finished_request = "xpath://span[text()='Finalizado']"
loc_finished_details_request = "xpath://mat-dialog-container//div[span[text()='Status']]/span[text()='Finalizado']"
loc_status_approved_renewal = "xpath://div[@class='header']//span[contains(text(), 'Solicitação de estágio Renovação')]//following-sibling::div//span[text()='Aprovado']"
loc_details_renewal = "xpath://div[@class='header']//span[contains(text(), 'Solicitação de estágio Renovação')]//ancestor::div[@class='card']//div[@class='buttonContainer']//button[span[contains(text(), 'Detalhes')]]"
loc_status_approved_credit = "xpath://div[@class='header']//span[contains(text(), 'Solicitação de aproveitamento de estágio')]//following-sibling::div//span[text()='Aprovado']"
loc_details_credit = "//div[@class='header']//span[contains(text(), 'Solicitação de aproveitamento de estágio')]//ancestor::div[@class='card']//div[@class='buttonContainer']//button[span[contains(text(), 'Detalhes')]]"
loc_status_finished_report = "xpath://div[@class='header']//span[contains(text(), 'Solicitação de estágio Obrigatório')]//following-sibling::div//span[text()='Finalizado']"
loc_details_report = "xpath://span[contains(text(), 'Finalizado')]/ancestor::div[contains(@class, 'card')]//p[contains(text(), 'Quantum Code LTDA')]//following::button//span[contains(text(), 'Detalhes')]"