#Lista de solicitações de estágios

loc_list_requests_internship = "xpah://div[@class='dataCard']/h2[contains(text(),'Estágios')]"
loc_type_intertnship_request = "css:.mat-mdc-card-title"
loc_name_student_request = "xpath://div[@class='titulo']"

loc_status_new_request = "css:.retangulo.statusColor4"
loc_status_analysis_request = "css:.retangulo.statusColor2"
loc_course_request = "xpath://div[@class='cardConteudo']/span[contains(text(),'Curso do aluno')]"
loc_date_request = "xpath://div[@class='cardConteudo']/span[contains(text(),'Data da solicitação:')]"
loc_analyze_request= "xpath://span[contains(text(),'Analisar')]"
loc_details_request = "xpath://span[contains(text(),'Detalhes')]"
loc_filter_name = "xpath://input[@name='filtroNome']"
loc_filter_new_radio = "id:mat-radio-3-input"
loc_filter_btn = "xpath://button[text()='Filtrar']"
loc_management_user = "id:cadS"
loc_header_courses = "xpath://a[text()='Cursos']"
loc_status__reject_request = "css:.retangulo.statusColor3"
loc_status_reject_text = "xpath://span[text()='Indeferido']"
loc_filter_reject_radio = "xpath://label[text()='Indeferidas']" #"xpath://input[@value='indeferidas']"