# formulário de estágio

loc_title_form = "css:.titulo"
loc_type_internship = "xpath://select[@name='tipo']"
loc_mandatory_internship = "xpath://option[@value='Obrigatório']"
loc_init_internship = "xpath://input[@name='inicioDataEstagio']"
loc_name_enterprise = "id:nomeEmpresa"
loc_end_internship  = "xpath://input[@name='finalDataEstagio']"
loc_contact_enterprise = "id:contatoEmpresa"
loc_integrating_agent_select = "xpath://select[@name='agente']"
loc_integrating_agent_option = "xpath://option[@value='CIEE']"
loc_salary = "id:salario"
loc_shift_select = "xpath://select[@name='turno']"
loc_shift_option = "xpath://option[@value='Manhã']"
loc_workload = "id:cargaHoraria"
loc_full_name = "xpath://input[@name='nomeCompleto']"
loc_course_name = "id:curso"
loc_registration = "id:matricula"
loc_tce_button = "css:.inputFileM"
loc_activity_plan = "css:.mat-mdc-tooltip-trigger.inputFileM"
loc_other_documents = "css:.mat-mdc-tooltip-trigger.fileInput"
loc_send_request = "css:.botao"
loc_observation_student = "css:.observacaoAluno"
loc_confirm_request = "css:.mdc-button__label"


